/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmpresaController;
import controller.ServicoController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Empresa;
import model.Servico;

/**
 *
 * @author Igor
 */
public class FusaoEmpresas extends javax.swing.JInternalFrame {

    private EmpresaController empresacontroller;
    private ServicoController servicocontroller;

    /**
     * Creates new form FusaoEmpresas
     */
    public FusaoEmpresas() {
        empresacontroller = new EmpresaController();
        servicocontroller = new ServicoController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmpresaOrigem = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmpresaDestino = new javax.swing.JFormattedTextField();
        btFundirEmpresas = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        jLabel1.setText("Empresa Origem:");

        try {
            txtEmpresaOrigem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Empresa Destino:");

        try {
            txtEmpresaDestino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btFundirEmpresas.setText("Efetuar Fusão");
        btFundirEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFundirEmpresasActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresaDestino))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFundirEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpresaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpresaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFundirEmpresas)
                    .addComponent(btCancelar))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btFundirEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFundirEmpresasActionPerformed
        try {
            Empresa empresaOrigem = empresacontroller.pesquisar(txtEmpresaOrigem.getText());
            Empresa empresaDestino = empresacontroller.pesquisar(txtEmpresaDestino.getText());

            if (empresaOrigem == null) {
                throw new Exception("Empresa Origem inexistente!");
            }

            if (empresaDestino == null) {
                throw new Exception("Empresa Destino inexistente!");
            }

            List<Servico> servicos = empresaOrigem.getServicos();
            for (int i = 0; i < servicos.size(); i++) {
                servicos.get(i).setEmpresa(empresaDestino);
                servicocontroller.salvar(servicos.get(i));
            }

            empresaOrigem.setServicos(null);
            empresacontroller.excluir(empresaOrigem);

            JOptionPane.showMessageDialog(this,
                    "Fusão das Empresas realizada com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Falha de Validação",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btFundirEmpresasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFundirEmpresas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txtEmpresaDestino;
    private javax.swing.JFormattedTextField txtEmpresaOrigem;
    // End of variables declaration//GEN-END:variables
}
